[package]
name = "method"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.3", default-features = false, features = ['std'] }
scheme-core = { path = "../../core" }

[build-dependencies]
cbindgen = "0.29.2"
cc = "1.2.46"
